name: My Another Pipeline

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      JOB: job
    steps:
      - name: rewrite-env
        env:
          JOB: step
        run: echo ${JOB}

      - name: check-env
        run: echo ${JOB}

      - name: github-env-1
        run: echo "GLOBAL=waiwai" >> $GITHUB_ENV

      - name: github-env-2
        run: echo ${env.GLOBAL}

      - name: set-1
        id: set-1-id
        run: echo '::set-output name=SET::hello'

      - name: set-2
        run: echo ${{ steps.set-1-id.outputs.SET }}
