name: My Another Pipeline

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: exit 1

      - name: step2
        run: echo step2

      - name: step3
        if: failure()
        run: echo step3