name: My Another Pipeline

on: [push]

env:
  WFENV: default1

jobs:
  MyJob:
    runs-on: ubuntu-latest
    env:
      JOBENV: default2
    steps:
      - name: git
        uses: actions/checkout@v3

      - name: echo env
        env:
          STEPENV: default3
        run: sh ./config.sh && echo ${WFENV}

      - name: echo ${WFENV}
        run: echo ${WFENV}

