name: My Another Pipeline

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: one-run 
        run: |
          readonly AAAA = 1111
          echo ${AAAA}
      - name: sep-run-1
        run: readonly BBBB = 2222
      - name: sep-run-2
        run: echo ${BBBB}
