name: My Another Pipeline

on: [push]

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: exit1

  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    steps:
      - name: step1
        run: echo b