name: My Another Pipeline

on: [push]

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo a
    outputs:
      condition: b

  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    if: needs.Job1.outputs.condition == 'b'
    steps:
      - name: step1
        run: echo b

  Job3:
    runs-on: ubuntu-latest
    needs: Job1
    if: needs.Job1.outputs.condition == 'c'
    steps:
      - name: step1
        run: echo c
  
  Job4:
    runs-on: ubuntu-latest
    needs: [Job2, Job3]
    if: always() && (needs.Job2.result == 'success' || needs.Job3.result == 'success')
    steps:
      - name: step1
        run: |
          echo ${{ needs.*.result[*] }}
          echo ${{ contains(needs.*.result, 'success') }}
          echo ${{ contains(needs.*.result, 'failure') }}
          echo ${{ contains(needs.*.result, 'skipped') }}