name: My Another Pipeline

on: [push]

env:
  WFENV: default1

jobs:
  Reuse:
    uses: ./.github/workflows/callee.yaml
    with:
      name: job
  
  MyJob:
    runs-on: ubuntu-latest
    needs: Reuse
    steps:
      - name: pickup-output
        run: echo ${{ needs.Reuse.outputs.message }}

      - uses: ./.github/workflows/callee.yaml
        with:
          name: hsaki
