name: My Another Pipeline

on: [push]

env:
  WFENV: default1

jobs:
  MyJob:
    runs-on: ubuntu-latest
    env:
      JOBENV: default2
    steps:
      - name: pwd
        id: pwd
        run: echo "::set-output name=pwd::$(pwd)"

      - name: echo pwd
        run: echo ${{ steps.pwd.outputs.pwd }}
