name: Callee

on:
  workflow_call:

env:
  WFENV: default4

jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      JOBENV: default5
    steps:
      - name: echo
        env:
          STEPENV: default6
        run: |
          echo ${WFENV}
          echo ${JOBENV}
          echo ${STEPENV}
  Job2:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo job2