name: Callee

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    outputs:
      message:
        value: ${{ jobs.Job1.outputs.message }}

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo message
        id: message-step
        run: |
          MESSAGE="hello, ${{ inputs.name }}"
          echo "::set-output name=message::${MESSAGE}"
    outputs:
      message: ${{ steps.message-step.outputs.message }}