name: My Test Pipeline

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - "deployment/qas"
      - "deployment/prd"
    types: [opened, reopened, closed]

jobs:
  Work:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.event.action }}
          echo ${{ github.base_ref }}
      - name: setup env
        run: |
          if ${{ contains(github.ref, 'refs/heads/feature') }} ; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif ${{ contains(github.head_ref, 'release/') }} \
                && [ "${{github.base_ref}}" == "deployment/qas" ] \
                && ${{ contains(fromJSON('["opened", "reopened"]'), github.event.action) }} ; then
            echo "ENV=qas" >> $GITHUB_ENV
          elif ${{ contains(github.head_ref, 'release/') }} && [ "${{github.base_ref}}" == "deployment/prd" ] && [ "${{github.event.action}}" == "closed" ] && [ ${{github.event.pull_request.merged}} == true ] ; then
            echo "ENV=prd" >> $GITHUB_ENV
          else
            echo "invalid env"
            exit 1
          fi
      - name: echo ${{ env.ENV }}
        run: echo ${{ env.ENV }}